### ISSUE TITLE
link loader problem of Multi2sim 4.2

### ISSUE THREAD

**Issue by MedicineYeh** [Multi2Sim/multi2sim#1]
I'm running multi2sim CPU only on my newest updates of packages of Arch Linux.
I wrote a hello world c program(just 6 lines in total, simply a printf) compiled with -m32 flag.
The, execute this program with m2s. (`m2s ./a.out`)

I got the following messages and the program did not execute since I didn't get the "hello world" message from my program.
How do I solve this problem? Any clue on this type of issue??

```
; Multi2Sim 4.2 - A Simulation Framework for CPU-GPU Heterogeneous Computing
; Please use command 'm2s --help' for a list of command-line options.
; Simulation alpha-numeric ID: OHp2r

Inconsistency detected by ld.so: rtld.c: 1235: dl_main: Assertion `rtld_ehdr->e_ehsize == sizeof *rtld_ehdr' failed!

;
; Simulation Statistics Summary
;

[ General ]
RealTime = 0.00 [s]
SimEnd = ContextsFinished

[ x86 ]
RealTime = 0.00 [s]
Instructions = 4659
InstructionsPerSecond = 5599760
Contexts = 1
Memory = 8544256
```

**Comment by MedicineYeh** [comment]
By some printf code injection, I found the message of `Inconsistency` is printed in function call `arch->active = emu->Run(emu);`  file src/arch/common/arch.c:374
Hope this information would help.
My GCC is `gcc version 5.3.0 (GCC)`. I tried gcc 4.8 as well, but it's not helpful.
The result of `ldd ./m2s`
```
        linux-vdso.so.1 (0x00007ffe92be9000)
        libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007f2090118000)
        libgdk-3.so.0 => /usr/lib/libgdk-3.so.0 (0x00007f208fe4b000)
        libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007f208fc3e000)
        libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007f208f9f3000)
        libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007f208f7cd000)
        libcairo-gobject.so.2 => /usr/lib/libcairo-gobject.so.2 (0x00007f208f5c4000)
        libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007f208f295000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007f208f06f000)
        libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f208ecf0000)
        libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f208ea9e000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f208e790000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f208e573000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f208e35d000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f208e058000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f208dcb7000)
        libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f208dab3000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f208d771000)
        libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f208d561000)
        libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f208d35b000)
        libatk-bridge-2.0.so.0 => /usr/lib/libatk-bridge-2.0.so.0 (0x00007f208d12c000)
        libepoxy.so.0 => /usr/lib/libepoxy.so.0 (0x00007f208ce38000)
        libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007f208cc22000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f208c9e3000)
        libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f208c7e0000)
        libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f208c5d5000)
        libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f208c3ca000)
        libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007f208c1c7000)
        libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f208bfc4000)
        libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007f208bd84000)
        libwayland-cursor.so.0 => /usr/lib/libwayland-cursor.so.0 (0x00007f208bb7c000)
        libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x00007f208b97a000)
        libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007f208b76b000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f208b559000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f208b351000)
        libthai.so.0 => /usr/lib/libthai.so.0 (0x00007f208b148000)
        libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0x00007f208af46000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f208ace2000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f208aa22000)
        libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007f208a77a000)
        libEGL.so.1 => /usr/lib/libEGL.so.1 (0x00007f208a575000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f208a371000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f208a13c000)
        libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f2089f38000)
        libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007f2089d2e000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f2089b0b000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f2089901000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f208968a000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f2089473000)
        libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f208926a000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f2088ffa000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2090a41000)
        libatspi.so.0 => /usr/lib/libatspi.so.0 (0x00007f2088dc9000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f2088b78000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f208894e000)
        libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007f2088746000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f208851b000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f208830b000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f2088035000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f2087e31000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f2087c2b000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f20879f9000)
        libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f2090b93000)
        libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f20877f5000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f20875cf000)
        liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f20873bd000)
        libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f20870db000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f2086ec7000)
```

**Comment by sunyifan112358** [comment]
Hi @rafaelubal @amirkavyan ,

I am also experiencing the same problem. Can you help with that? This problem only happens with a new version of Ubuntu after 14.04. I am not sure it is caused by a newer version of glibc or something else. 

Thanks,
Yifan

**Comment by sunyifan112358** [comment]
Hi @MedicineYeh,

I also have this problem. But Ubuntu 14.04 works for me. 

Thanks,
Yifan

**Comment by MedicineYeh** [comment]
Yes, we can run it on Ubuntu 14.04. If this problem could be solved, that would be even better! You have such good work which shouldn't be a legacy code after few years. :D I think this might be some ABI changes or linker API changes causing this inconsistency problem. 
By the way, I tried the `hello world` program compiled Ubuntu 14.04 with the Multi2Sim on my Arch Linux. It works. The compiling flag is `-m32 --static` to make it independently runnable. XDDD

**Comment by MedicineYeh** [comment]
I'm now sure the problem is caused by /lib/ld-linux.so.2 (/usr/lib32/ld-linux.so.2). I still don't know the exact problem that causes the header size assertion error. 
There are some changes after version 2.23 (http://repo.or.cz/w/glibc.git/blob/HEAD:/elf/rtld.c). It might and might not be the cause.
``` C
1220   /* Set up the program header information for the dynamic linker
1221      itself.  It is needed in the dl_iterate_phdr callbacks.  */
1222   const ElfW(Ehdr) *rtld_ehdr;
1223 
1224   /* Starting from binutils-2.23, the linker will define the magic symbol
1225      __ehdr_start to point to our own ELF header if it is visible in a
1226      segment that also includes the phdrs.  If that's not available, we use
1227      the old method that assumes the beginning of the file is part of the
1228      lowest-addressed PT_LOAD segment.  */
1229 #ifdef HAVE_EHDR_START
1230   extern const ElfW(Ehdr) __ehdr_start __attribute__ ((visibility ("hidden")));
1231   rtld_ehdr = &__ehdr_start;
1232 #else
1233   rtld_ehdr = (void *) GL(dl_rtld_map).l_map_start;
1234 #endif
1235   assert (rtld_ehdr->e_ehsize == sizeof *rtld_ehdr);
1236   assert (rtld_ehdr->e_phentsize == sizeof (ElfW(Phdr)));
```
By the way, I used the `/lib/ld-linux.so.2` copied from Ubuntu 14.04 on my own computer. It does not have the problem of __Assertion `rtld_ehdr->e_ehsize == sizeof *rtld_ehdr' failed!__, though it causes a seg fault on loading shared libraries `/usr/lib32/libc.so.6`. :P 
One more thing, static linked binary does not have this assertion problem.

**Comment by ckalra** [comment]
Any updates on this issue? I am getting the same error on Ubuntu 16.04.

**Comment by MedicineYeh** [comment]
You just need to compile your program in statical linking. It would work around the link loader issue.

**Comment by amirkavyan** [comment]
You can also, for now, copy both ld.so and libc.so from the 14.04 to 16.04,
create symbolic links for them (ld-linux.so.2 and libc.so.6), and compile
your binary dynamically with:
gcc main.cc -Wl,--rpath=<path to the symbolic link for new libc.so>
-Wl,--dynamic-linker=<the new ld-linux.so.2 file itself>.

**Comment by afranques** [comment]
I'm using Ubuntu 16.04, I had the same problem, compiling the `hello-world.c` with gcc with the `--static` flag solved the problem for me. Thanks for the help!

**Comment by Akshaykanth** [comment]
I'm using Ubuntu 16.04 LTS, I have the same problem but apparently `--static` flag isnt doing the job. Would be a great help if anyone could help?

**Comment by afranques** [comment]
What is the output of the error? Have you tried compiling with also the `-m32` flag? The input binaries must be 32 bits.

**Comment by Akshaykanth** [comment]
Output: 

; Multi2Sim 5.0 - A Simulation Framework for CPU-GPU Heterogeneous Computing
; Please use command 'm2s --help' for a list of command-line options.
; Simulation alpha-numeric ID: CCnXn

**Inconsistency detected by ld.so: rtld.c: 1237: dl_main: Assertion `rtld_ehdr->e_ehsize == sizeof *rtld_ehdr' failed!**

;
; Simulation Statistics Summary
;

[ General ]
RealTime = 0.00 [s]
SimEnd = ContextsFinished

[ x86 ]
RealTime = 0.00 [s]
Instructions = 4855
InstructionsPerSecond = 2603217

I do compile my file as `gcc -m32 --static `

**Comment by afranques** [comment]
Have you tried using as an input a simple hello-world?, like:

`#include <stdio.h>

int main()
{
    	printf("Hello World");
	return 0;

}`

To see if the problem is the input file or the simulator

**Comment by Akshaykanth** [comment]
Okay,  the hello_world program works properly as per required (i just tried) . The sample programs that comes with the multi2sim 5.0 does not work . I think this would suffice me with my project. 
But i would like to know what exactly is the error ? and the even the Context and Memory is not being displayed.
Thanks a lot @afranques

**Comment by afranques** [comment]
If you're already compiling with --static, I don't know what the error might be saying. In my case I stopped digging as soon as --static solved the problem. Let's see if someone else can give a better insight

**Comment by amirkavyan** [comment]
Thank you @afranques and @MedicineYeh for helping  out :)

@Akshaykanth are you trying to compile opencl host codes? If so, are you linking the m2s opnecl runtime library statically too?

The command probably looks something like this:
gcc vector-add.c -o vector-add -lm2s-opencl -I$M2S_ROOT/runtime/include -L$M2S_ROOT/lib/.libs -static

**Comment by ttungl** [comment]
Hi,
I have tried with Ubuntu 16.04 but it did not work. I got the same issue as @Akshaykanth, and followed all ways of @afranques, but still not work out. I re-install Ubuntu 14.04 and got rid of this issue without any problem. Since I still want to know why we get this error, after looking into the README file, it seems like the installation guide is slightly different from the manual guide. 

> Installation:
> 
> In order to install Multi2sim on Ubuntu 14.04 and 15.04 run the following commands:
> 
> $> libtoolize
> $> aclocal
> $> autoconf
> $> automake --add-missing
> $> ./configure
> $> make
> 
> For other platforms such as Mac OS and Windows (and for now, Ubuntu 16.04) you can use our up to
> date image on docker. For that you require to have docker installed on your machine. 
> The instructions to install docker can be found in: https://docs.docker.com/engine/installation/
> 
> After installing the docker, you can pull the image of the Multi2sim's master branch with the
> following command:
> 
> (in the docker terminal)
> $> docker pull multi2sim/multi2sim
> 
> $> docker run -it multi2sim/multi2sim bash
> 
> The head of the master branch of Multi2sim 5.0 is automatically compiled and installed on the 
> filesystem of the downloaded image, and you can simply run Multi2sim:
> 
> $> m2s

I did not try this way out, it could be the case of this issue in Ubuntu 16.04.
Best,

**Comment by MedicineYeh** [comment]
Hi, @ttungl . Yes, these are steps that reset and fetch your system library version info and some other things. It only needs to be done once, but I put it into my config shell scripts. So... yes, you are right.
Thanks for providing the docker solution here. :D

**Comment by ttungl** [comment]
Thanks @MedicineYeh, it would be nice if someone can give a try on whether this way works out on Ubuntu 16.04.

**Comment by Akshaykanth** [comment]
@amirkavyan : Hey..! Iam not using a openCL host so that command didnt work.Thanks

@ttungl : Hey..! The docker solution is actually cool. It worked right for a certain codes for others the same error persists. Thank you anyways.

**Comment by rafaelubal** [comment]
Hi all,

The problem turned out to be in the program loading process, implemented in `src/arch/x86/emulator/ContextLoader.cc`.

The content of an ELF executable is pointed to by two indexes located at the head of the file, called "section headers" and "program headers". The section headers point to "sections", and the program headers point to "segments". The content pointed to by sections and segments may overlap.

Multi2Sim's implementation of the program loading process was based on traversing the sections of the ELF file, and loading into memory those with the appropriate values in the 'sh_type' and 'sh_flags' in the corresponding section headers. This seemed to load all information needed to start running ISA instructions.

Or at least that was the case until recent versions of binutils, and more specifically, the dynamic loader (a.k.a. program interpreter) in "/lib/ld-linux.so". It turns out that there is a part of the ELF file that is not pointed to by any section, which is the header of the ELF file itself. And for some reason that I didn't dig into, the dynamic loader now decides to read that ELF header from the virtual memory image of the loaded process, and assert()'s that it was found.

The solution consisted in modifying the program loading process in order to traverse the ELF file through its segments, instead of the sections, and load into memory those segments that have the PT_LOAD flag set in their associated program header. This turned out to be a simpler process, since in most cases only two segments (text and data) cover all the loadable content required by an application. And now the ELF file header required by the dynamic linker is in fact included within a segment.

For those interested in further reading, these two documents contain most information needed to understand program loading:

System V Application Binary Interface (ABI):
http://www.sco.com/developers/devspecs/abi386-4.pdf

Executable and Linkable (ELF) format specification:
http://www.skyfree.org/linux/references/ELF_Format.pdf

Thanks @MedicineYeh for pointing into the right direction.
