### ISSUE TITLE
where to add new replacement policy name 

### ISSUE THREAD

**Issue by Manas-pandey** [Multi2Sim/multi2sim#12]
i am trying to run my own replacement policy (MRU) in cache.c  .i have made changes in enum cache_policy_t and struct str_map cache_policy_map but i still get error saying my error saying invalid cache replacement policy.where to add the name for new replacement policy.

**Comment by amirkavyan** [comment]
The code you are referring to was within the multi2sim 4.2 (which is in C). That version is now deprecated. The github is to support multi2sim 5.0, which is implemented in C++

Additionally, please use the forum in https://topoftrees.com/Multi2Sim/Multi2Sim/forum for questions. The "issues" section of the github page is only used among the developers for enhancing the multi2sim framework, and not implementing new or experimental features. 

After porting your implementation to C++, we can help you (through the forum in topoftrees.com) in finishing this implementation.

**Comment by Manas-pandey** [comment]
Thanks a lot for getting back to me on the query. looking forward to
explore the forum .
