### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by MedicineYeh** [Multi2Sim/multi2sim#2]
[Official Website](https://www.multi2sim.org/) is down. It redirects to your University's homepage of Engineering Department. Please kindly check it out. :D

**Comment by amirkavyan** [comment]
Medicine,

the multi2sim website is now changing to its new domain, which follows:

http://www.coe.neu.edu/research/multi2sim/

Multi2sim website eventually get redirected to this website.

Also we will look into the reported bug with the 15.04, to resolve the
issue.

Kavi

**Comment by MedicineYeh** [comment]
Great! It looks much better than the previous one!! Though sometimes the menu disappears on my browser(both Safari and Chrome).
Thanks for your effort on the bug of Multi2Sim. I really appreciate that!
