### ISSUE TITLE
on x86 lack some syscalls

### ISSUE THREAD

**Issue by siscof** [Multi2Sim/multi2sim#3]
the lastest m2s version launch me this error:

    ; Multi2Sim 5.0 - A Simulation Framework for CPU-GPU Heterogeneous Computing
    ; Please use command 'm2s --help' for a list of command-line options.
    ; Simulation alpha-numeric ID: DZTS6

    [x86] [pid 1000] [eip 0x81131a2] Error: Invalid system call (code 329)

whe I run southen-Islands benchmarks 2.5  it seems that lack some syscalls. Is multi2sim 5.0 under develoment yet?

**Comment by amirkavyan** [comment]
@rafaelubal this should be marked as closed now, right?

**Comment by rafaelubal** [comment]
I guess so. I can't tell what system call that is right now. But all
benchmarks are running.
