### ISSUE TITLE
Which CUDA SDK version is supported?

### ISSUE THREAD

**Issue by Oliver-Piorun** [Multi2Sim/multi2sim#41]
Hey, I am wondering which version of the CUDA SDK is ready to use with the latest version of Multi2Sim?

CUDA 4.0 is listed in the documentation (which is a bit old) but here on github there is a "m2s-bench-cudasdk-6.5" repository. So is CUDA 6.5 supported?

Thanks in advance!

**Comment by gxkepler** [comment]
Hi,

The CUDA 6.5 is supported. You should use the IISWC branch for running CUDA
benchmarks.

Thanks!

**Comment by Oliver-Piorun** [comment]
Thank you!
