### ISSUE TITLE
multi2sim-4.2 AMD benchmarks

### ISSUE THREAD

**Issue by mahbod72** [Multi2Sim/multi2sim#48]
I want to use multi2sim-4.2 but the AMD benchmarks that already placed at multi2sim.org (that are suitable for multi2sim-5.0) are not executable on multi2sim-4.2. So I can't run AMD benchmarks on southern-islands or evergreen.
Any help will be appreciated

**Comment by xianggong** [comment]
Hi,

You might need to use an older gcc to recompile the host program. The binary on Multi2Sim.org is compiled with a newer gcc, which may generate some instructions/syscalls that are not supported in Multi2Sim 4.2. The source code is available here https://github.com/Multi2Sim/m2s-bench-amdsdk-2.5-src. 

We didn't change the format of kernel binaries. So it should be OK to use the kernel binaries.

**Comment by mahbod72** [comment]
Which gcc version do you suggest?

**Comment by xianggong** [comment]
Multi2Sim 4.2 was developed on Ubuntu 12.04, I think it has GCC 4.4.

**Comment by mahbod72** [comment]
Thanks a lot
