### ISSUE TITLE
FATAL: Kernel too old

### ISSUE THREAD

**Issue by chiec** [Multi2Sim/multi2sim#62]
Hello, I'm trying to do some research using m2s, but I keep runing into the same error again and again. After compiling the sources:
```
$> libtoolize
$> aclocal
$> autoconf
$> automake --add-missing
$> ./configure
$> make
```
When I try to run a simple example I keep getting "FATAL: Kernel too old"

; Multi2Sim 5.0 - A Simulation Framework for CPU-GPU Heterogeneous Computing
; Please use command 'm2s --help' for a list of command-line options.
; Simulation alpha-numeric ID: Zg8MD

FATAL: kernel too old

```
[chiec@proxima example-1]$ ../../../bin/m2s ./test-args asdf
;
; Simulation Statistics Summary
;

[ General ]
RealTime = 0.00 [s]
SimEnd = ContextsFinished

[ x86 ]
RealTime = 0.00 [s]
Instructions = 19027
InstructionsPerSecond = 4324318
```
I get the same using an even simplier "hello world", and if I compile it statically I also get "RunSignalHandler: invalid signal handler" 

The kernel too old error seems to be a mismatch between the kernel and the glibc version but afaik it doesn't have much sense (kernel 4.15.4 glibc 2.26 on fedora27). In a Ubuntu 17.10 I have the exact same errors.

Thank you!

**Comment by qfettes** [comment]
Was there ever a resolution to this issue?

**Comment by cmanso** [comment]
> Was there ever a resolution to this issue?

src/arch/x86/emulator/ContextSyscall.cc l3213 (https://github.com/Multi2Sim/multi2sim/blob/master/src/arch/x86/emulator/ContextSyscall.cc#L3213)

You have to change the answer to the syscall to a newer kernel (use "uname -a" to look the info of your current one)
