### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by qfettes** [Multi2Sim/multi2sim#69]
Hello I'm attempting to run multi2sim on Ubuntu 18.04. The Linux kernal is 4.15.0 and the gcc version is 7.3.0. The simulator compiles without issue. However, upon running the sample in multi2sim-5.0/samples/x86/example-4/ I get the following output:

`gcc test-threads.c -o test-threads -lpthread -m32 -static`
`$M2SROOT/bin/m2s --x86-sim detailed --x86-config x86-config.ini --ctx-config ctx-config.ini`

Output:

`; Multi2Sim 5.0 - A Simulation Framework for CPU-GPU Heterogeneous Computing
; Please use command 'm2s --help' for a list of command-line options.
; Simulation alpha-numeric ID: Nzo2e

FATAL: kernel too old

RunSignalHandler: invalid signal handler`

**Comment by vsn97** [comment]
Hey @qfettes 

Edit the kernel version in your src/arch/x86/emulator/ContextSyscall.cc file. It should be somewhere near the 3100th line, inside a function.

**Comment by stardica** [comment]
Compile the app to be run inside of M2S with an older version of GCC. Like
4.6 or so. The x86 emulator is built to emulate older versions of linux,
which GCC is design to compile for. Dialing back the GCC compiler works for
me.

Chris G.

**Comment by vsn97** [comment]
Thanks Chris. Do you have any ideas about the ARM compilation?

**Comment by stardica** [comment]
Nope sorry. I've only ever used it for the x86 cpu model.

Chris G.
