### ISSUE TITLE
isnan was not declare in this scope (FIXED)

### ISSUE THREAD

**Issue by MedicineYeh** [Multi2Sim/multi2sim#8]
In newest commit (20th March.), there's an error (only one) when compiling multi2sim.

According to this thread.
http://stackoverflow.com/questions/18128899/is-isnan-in-the-std-namespace-more-in-general-when-is-std-necessary-optio

In newer gcc version, `isnan` is not included when one include `cmath.h`. The error message is as follows
```
multi2sim/src/arch/kepler/emulator/ThreadIsa.cc:4585:47: error: ‘isnan’ was not declared in this scope
    cmp_result = ((src1 < src2) && (!isnan(src1)) && (!isnan(src2)));
                                               ^
multi2sim/src/arch/kepler/emulator/ThreadIsa.cc:4585:47: note: suggested alternative:
In file included from /home/medicineyeh/Projects/m2s/multi2sim/src/arch/kepler/emulator/ThreadIsa.cc:20:0:
/usr/include/c++/5.3.0/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
multi2sim/src/arch/kepler/emulator/ThreadIsa.cc:4587:48: error: ‘isnan’ was not declared in this scope
    cmp_result = ((src1 == src2) && (!isnan(src1)) && (!isnan(src2)));

......

```
I could solve it by adding `using namespace std;` after includes in file `src/arch/kepler/emulator/ThreadIsa.cc`. Or, substitute all `isnan` by `std::isnan`.

**Comment by rafaelubal** [comment]
Thanks for pointing this out. Fixed now.
